### ISSUE TITLE
Add restrictions and validation of kickstarter fundraisers

### ISSUE THREAD

**Issue by curtislacy** [mastercoin-MSC/mastercoin-tools#10]
See the spec: https://github.com/mastercoin-MSC/spec

**Comment by curtislacy** [comment]
Note on token locking - when we spend MSC to purchase another token from a fundraiser, the MSC are locked, but not the tokens we bought.  Those can be traded immediately.

**Comment by ghost** [comment]
Fair enough, but for this issue, it would really be helpful if we had test cases: Otherwise, I'm really just shooting in the dark here. The CLI tools have been out there long enough that people should have had a chance to use them and report usability issues, and I really don't feel like there is any reason technically stopping us from having test case transactions at this point in the month.

I've only really thought about Smart Property for less than 2 weeks, and I know there are others out there who have a better grasp of what could go wrong than I ever possibly could

**Comment by curtislacy** [comment]
The simple cases, you can handle pretty easily (don't accept payments if the fundraiser is closed, that sort of thing).  Marv and I are working on a sequence of transactions that test more of the edge cases - once we've got that, we'll shove a bunch of transactions on the blockchain and you and Zathras will have a pretty good set of test data, I think.
