### ISSUE TITLE
Update CLI issuance tool to support "Live" (Non-MSC) properties

### ISSUE THREAD

**Issue by curtislacy** [mastercoin-MSC/mastercoin-tools#11]
This should really just be throwing a switch, so let's do it early in the week.

**Comment by ghost** [comment]
Ok so, on further thought this does need some explaining, not too much though:

Right now our CLI tool supports sending Live properties , but they will be marked invalid by the validator engine since its not the right block yet. Does this mean flip the switch and allow live currencies, or just to have capability to send live currencies (which exists)?
